cloud:
  aws:
    credentials:
      access-key: ${ACCESS-KEY}
      secret-key: ${SECRET-KEY}
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: huellapp

spring:
  sevlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 50MB
      max-request-size: 10MB